"""empty message

Revision ID: a203d12ab20f
Revises: e4347d83ec8f
Create Date: 2018-04-04 23:36:52.753143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a203d12ab20f'
down_revision = 'e4347d83ec8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', sa.String(length=100), nullable=False))
    op.drop_column('article', 'titile')
    op.add_column('role', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'confirmed')
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_column('role', 'permissions')
    op.drop_column('role', 'default')
    op.add_column('article', sa.Column('titile', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('article', 'title')
    # ### end Alembic commands ###
